#pragma once
#define CAN_OUTPUT_RST 17

#define LCD_OUTPUT_DC 7
#define LCD_OUTPUT_RST 8
#define LCD_OUTPUT_BACKLIGHT 9
#define LCDLEFT_SPI_CS 10
#define LCDCENTER_SPI_CS 11
#define LCDRIGHT_SPI_CS 12

#define BTN_HAZARD 46
#define BTN_WIPER 52
#define BTN_LSIG 50
#define BTN_RSIG 44
#define BTN_HEADLIGHT 48
#define BTN_HORN 42
//#define BTN_RADIO 54

#define NUM_BUTTONS NUMSTATES